# Use official Python image as base
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set default superuser credentials (you can change these to fit your needs)
ENV DJANGO_SUPERUSER_USERNAME=admin
ENV DJANGO_SUPERUSER_PASSWORD=zxcvbnm10

# Set working directory inside the container
WORKDIR /app

# Copy the requirements and install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt


# Copy the entire Django project into the container
COPY . /app/

# Expose the Django application port
EXPOSE 8000

# Ensure a fresh database by deleting the old one
RUN rm -f /app/db.sqlite3
# Run database migrations and create a superuser without email
RUN python manage.py migrate && \
    python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('$DJANGO_SUPERUSER_USERNAME', '', '$DJANGO_SUPERUSER_PASSWORD')" || true

# Start the Django application with Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "todo_backend.wsgi:application"]
