# Generated by Django 5.1.4 on 2025-03-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_category_remove_task_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
